core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_interface.urls', namespace='user_interface')),
    path('api/v1/', include('referral_system.urls')),
    path('api/v1/', include('user.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_interface/urls.py
from django.urls import path
from . import views
from user_interface.apps import UserInterfaceConfig

app_name = UserInterfaceConfig.name

urlpatterns = [
    path('logout/', views.logout_func, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('', views.enter_phone_number, name='enter_phone'),
    path('enter_code', views.enter_verification_code, name='enter_code'),
    path('activate_referral_code', views.enter_referral_code, name='activate_referral_code'),
]

user_interface/models.py
from django.db import models

# Create your models here.

user_interface/forms.py
from django import forms


class PhoneNumberForm(forms.Form):
    phone_number = forms.CharField(max_length=15, label='Phone Number')


class VerificationCodeForm(forms.Form):
    verification_code = forms.CharField(max_length=4, label='Verification Code')

user_interface/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from referral_system.models import Referral
from django.shortcuts import redirect
from django.shortcuts import render

from referral_system.services.referral_system_manager import ReferralSystemManager
from user.models import User
from user.services.phone_auth_manager import PhoneAuthManager
from user_interface.forms import PhoneNumberForm, VerificationCodeForm


def logout_func(request):
    logout(request)
    return redirect('user_interface:enter_phone')


def enter_phone_number(request):
    if request.method == 'POST':
        form = PhoneNumberForm(request.POST)
        if form.is_valid():
            number = form.cleaned_data['phone_number']
            data = {'phone': number}
            PhoneAuthManager(data=data).process_user()
            request.session['phone_number'] = number
            return redirect('user_interface:enter_code')
    else:
        form = PhoneNumberForm()
    return render(request, 'user_interface/enter_phone.html', {'form': form})


def enter_verification_code(request):
    error_message = None
    if request.method == 'POST':
        form = VerificationCodeForm(request.POST)
        if form.is_valid():
            entered_code = form.cleaned_data['verification_code']
            phone = request.session.get('phone_number')
            user = User.objects.filter(phone=phone, auth_code=entered_code).first()
            if not user:
                error_message = "Неверный проверочный код"
                form = VerificationCodeForm()
                return render(request, 'user_interface/enter_code.html', {'form': form, 'error_message': error_message})
            login(request, user)
            ReferralSystemManager(user=user).get_referral_code()
            return redirect('user_interface:profile')
    else:
        form = VerificationCodeForm()
    return render(request, 'user_interface/enter_code.html', {'form': form, 'error_message': error_message})


def all_user_events(request):
    return render(request, 'user_interface/base.html')


@login_required
def profile(request):
    user = request.user
    referral_info = Referral.objects.filter(user=user).first()
    error_info = request.session.get('error_message')
    return render(request, 'user_interface/profile.html',
                  {'user': user, 'referral_info': referral_info, 'error_info': error_info})


@login_required
def enter_referral_code(request):
    error_message = None
    if request.method == 'POST':
        referral_code = request.POST.get('referral_code')
        user = request.user
        try:
            manager = ReferralSystemManager(user=user)
            manager.activate_referral_code(referral_code)
        except Exception as e:
            error_message = e.detail['error']
            request.session['error_message'] = error_message
    return redirect('user_interface:profile')

user_interface/templates/user_interface/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Моя Страница{% endblock %}</title>
    <!-- Подключаем Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .navbar {
            background-color: #343a40 !important; /* Цвет фона навигационной панели */
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="/">На главную</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link btn text-white font-weight-bold"
                               href="{% url 'user_interface:enter_phone' %}">Авторизация</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link btn text-white font-weight-bold"
                               href="{% url 'user_interface:profile' %}">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn text-white font-weight-bold" href="{% url 'user_interface:logout' %}">Выйти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- Основное содержимое -->
<div class="container mt-5">
    {% block content %}
    {% endblock %}
</div>

<!-- Подключаем Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

user_interface/templates/user_interface/enter_code.html
{% extends 'user_interface/base.html' %}

{% block content %}
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div style="width: 400px; padding: 20px; border: 1px solid #ccc; border-radius: 5px; background-color: #f9f9f9; text-align: center;">
            <h2>Введите верификационный код</h2>
            {% if error_message %}
                <div style="color: red; margin-bottom: 10px;">
                    {{ error_message }}
                </div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit"
                        style="width: 100%; padding: 10px; background-color: #007bff; color: #fff; border: none; border-radius: 5px; cursor: pointer;">
                    Submit
                </button>
            </form>
        </div>
    </div>
{% endblock %}

user_interface/templates/user_interface/enter_phone.html
{% extends 'user_interface/base.html' %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
  <div style="width: 400px; padding: 20px; border: 1px solid #ccc; border-radius: 5px; background-color: #f9f9f9;">
    <h2 style="text-align: center;">Введите ваш номер телефона</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" style="display: block; width: 100%; padding: 10px; margin-top: 10px; background-color: #007bff; color: #fff; border: none; border-radius: 5px; cursor: pointer;">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

user_interface/templates/user_interface/profile.html
{% extends 'user_interface/base.html' %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
  <div style="width: 400px; padding: 20px; border: 1px solid #ccc; border-radius: 5px; background-color: #f9f9f9; text-align: center;">
    <h2>Профиль</h2>
    <p>Телефон: {{ user.phone }}</p>
    <p>Ваш реферальный код: {{ user.referral_code.number }}</p>

    {% if referral_info %}
      <p>Вы уже использовали реферальный код: {{ referral_info.referral_code.number }}</p>
    {% endif %}

    {% if error_info %}
      <p style="color: red;">{{ error_info }}</p>
    {% endif %}

    {% if not referral_info %}
    <form method="post" action="{% url 'user_interface:activate_referral_code' %}">
        {% csrf_token %}
        <input type="text" name="referral_code" placeholder="Enter Referral Code">
        <button type="submit" style="margin-top: 10px; background-color: #007bff; color: #fff; border: none; border-radius: 5px; padding: 10px; cursor: pointer;">Submit</button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock %}